"""Bind each remaining image request to current copy and the art director's brief.

This prepares requests only. Images must be generated by image_gen.imagegen,
inspected individually, and selected in prompts.json before print production.
"""
from pathlib import Path
import json, hashlib
R=Path(__file__).resolve().parents[4]
P=R/'working/v2.7'
B=P/'visual/art_direction/FOULWAKE_121_ART_BRIEF_MANIFEST_v2.7.json'
OUT=P/'visual/full_deck_20260907'
COMMON='''Create ONE finished original illustration for FOULWAKE, a 1721 maritime social-deduction board game. The supplied KAPTAN image is an ART LANGUAGE reference only: confident living ink outlines, dense but purposeful engraved crosshatching, warm weathered cream paper, matte navy, dull ochre and rust. Use observed expressive human caricature and convincing wood, hemp, wet wool, stone and sea. Carry the style, never the captain's face, hat insignia, crossed arms, bird, exact ship, border, typography or card layout. This is only the artwork that will be placed inside a separately typeset card.
One clear action and focal relationship, material weight, restraint and emotional specificity. All necessary anatomy and equipment must be coherent: two arms per person, correctly joined fingers, believable perspective, people proportional to a real vessel, mast/rigging/deck/hull connected. No doll-sized ships with giant sailors. Main subject and important hands/objects completely inside image, about 5 percent edge safety. Camera and silhouette must follow the individual brief, not a uniform portrait or repeated tableau. A calm region is allowed; do not draw a blank text panel.
Absolutely NO letters, numbers, text, pseudo-handwriting, names, signs, labels, compass lettering, brand marks, crests, speech balloons, frames, banner, watermark, user interface or card mockup. If a paper is required, show blank fibres, stains, creases or indistinct coast contours, never glyph-like scribbles. Card name and game copy below are CONTEXT ONLY, not text to draw. No generic pirate skulls, gore, celebratory hero pose, photorealism, glossy 3D, airbrush, modern clothes or industrial equipment. No extra pets or birds unless explicitly required by this individual subject. No magical glow. No franchise character likeness. Humor only if required by the specific brief, from the physical situation or institution, never mocking a victim. Character identity must not imply loyalty or reveal hidden information.
The following Turkish art brief is authoritative for this distinct image. Interpret it visually; do not print it:
'''
OVERRIDES={
 'GUC-04':'Resolve the concealed-object action physically: an anonymous hand lowers ONE linen-wrapped personal object through the narrow opening of a wooden chest. The lid may be slightly ajar; the object stays concealed. Do not put an object through a solid closed lid.',
 'GUC-23':'Keep the dark humor physically plausible: the hardtack rests against the edge of the thin table while hands bear down on it; a small existing wood split at that pressure point carries the joke. Do not make a suspended biscuit magically crack a distant table.',
 'KAR-09':'Freeze one instant of trying a key: exactly three modest forged keys on a hand-sized ring, one engaged in the lock, the other two hanging. No oversized fantasy keys and no sequence panels.',
 'KAR-12':'The wooden chip is one small unmarked token falling from the lookout platform. Below is a physically credible full-scale deck with rigging, not a schematic game board or drawn UI. No arrows, numerals or instructions.',
 'KAR-20':'Freeze one knock with two knuckles touching the mast. Do not draw multiple exposure hands or marks counting three. The action count is conveyed by card text outside the art.',
 'GUC-08':'Object-led extreme close-up: aged hands and divider tips on damp blank rag paper, no portrait. This must differ from the young cartographer character scene.',
 'GUC-15':'Use a plain battered brown felt three-cornered hat with NO crest, no feather, no bird, no gold braid. It must not resemble the binding captain hat. One approaching vote token is the main action; any greeting gesture is understated.',
 'GUC-17':'The bird is an old small African grey parrot with a restrained muted red tail, shown on a freestanding plain wooden perch. Distinct from KAR-15\'s larger green parrot. No costume or human eye anatomy.',
 'KAR-15':'Use one larger muted green parrot with a horn-coloured beak on a rope chest beside the woman, not perched on her shoulder. Her broad diamond face, short coarse curls and balanced stout posture are essential.',
 'SAD-H-01':'Only the apothecary\'s plain sleeve and hand are visible. Do not depict or identify Veyr, a sick child, a villain, or a benevolent saint. Two people, two visible hands, one small stoppered glass vial, one closed ordinary ledger.',
 'SAD-H-04':'An anonymous adult, distinct from all Character faces, studies the torn LOWER EDGE of a half sheet. Blank and stained paper, no name. No doctor, laboratory, corpse or proof of guilt.',
 'SAD-T-05':'Anonymous physician hands protect stained blank experimental pages, face out of frame. No verified cure, named portrait, modern syringe or microscope.',
 'SAD-T-08':'A low anonymous empty grave plot is in the near foreground; an ordinary traveller seen from behind turns toward a living distant port. No skeleton, ghost, name, readable headstone, cross as faction emblem, or mocking a dead person.',
 'SAD-T-09':'A rough index finger follows an unlettered ledger page with faint physical ruled grooves and blank rows. No glyphs, no signature. The withheld quill stays secondary.',
}
FIELDS=['first_two_seconds_emotion','visual_narrative_aim','subject_character_event_identity','age_face_body_silhouette_or_event_main_form','single_main_action','real_ship_sea_coast_location','card_specific_object_or_visual_metaphor','framing_viewpoint_focus_negative_space','line_hatching_palette_approach','secondary_wordless_joke_max_one','similarity_risk_with_other_cards','specifically_do_not_repeat_face_pose_scene_animal_humor','visual_rhythm_role_in_deck','period_and_world_check']
def main():
 b=json.loads(B.read_text()); records=[]
 amendments=json.loads((Path(__file__).parent/"director_amendments.json").read_text())
 for x in b['records']:
  ident=x['card_identity'];id=ident['id']
  if ident['pilot_selected']:continue
  orientation='portrait, 1024 by 1536' if id.startswith('KAR-') and id not in ('KAR-08','KAR-11','KAR-12') else 'landscape, 1536 by 1024'
  brief={k:x[k] for k in FIELDS}
  prompt=COMMON+json.dumps({'internal_id_do_not_print':id,'context_name':ident['exact_name'],'context_flavor_do_not_print':x['exact_copy'].get('flavor',''),**brief},ensure_ascii=False,indent=2)
  prompt+='\nDIRECTOR CLARIFICATION: '+OVERRIDES.get(id,'Preserve the distinct protected intent and coherent single physical action. No unnecessary secondary joke.')
  if id.startswith('SAD-'):
   prompt+='\nLOYALTY ART: private remembered motivation, not a separate objective. Hands, ordinary clothes and partial anonymous profiles differ from all named Character cards. Use the same human, warm paper palette for both teams; no moral colour coding.'
  prompt+='\nOUTPUT: one '+orientation+' textless illustration, not a sheet of variants or a card design.'
  prompt+=amendments.get(id,'')
  records.append({'id':id,'name':ident['exact_name'],'family':ident['front_family'],'prompt':prompt,'references':['working/v2.7/visual/references/FOULWAKE_KAPTAN_ART_LANGUAGE_REFERENCE_v2.7.jpg'],'brief_git_blob':'28c1100615548b07e527cf50f32071e42c63f5bb','canonical_copy_sha256':hashlib.sha256(json.dumps(x['exact_copy'],ensure_ascii=False,sort_keys=True).encode()).hexdigest(),'asset_path':f'working/v2.7/visual/full_deck_20260907/assets/{id}.png','status':'PLANNED'})
 assert len(records)==109 and len({r['id']for r in records})==109
 OUT.mkdir(parents=True,exist_ok=True)
 (OUT/'generation_plan.json').write_text(json.dumps({'task_id':'FOULWAKE-FULL-DECK-ART-001','source_commit':'b510c783ca6361748302e2bad61f72d42034e236','brief_sha256':hashlib.sha256(B.read_bytes()).hexdigest(),'records':records},ensure_ascii=False,indent=2)+'\n')
 print('109 distinct image requests bound to exact source copy and individual briefs.')
if __name__=='__main__':main()
